# Generated by Django 3.1 on 2020-08-11 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('developer_name', models.CharField(max_length=50)),
                ('developer_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=50)),
                ('project_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('project_type', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('year', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50)),
                ('developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.developer')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projecttask')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=50)),
                ('support_staff', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('assignment_date', models.DateField(null=True)),
                ('developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.developer')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
    ]
